- name: "Setup docker"
  include_role:
    name: geerlingguy.docker
    tasks_from: setup-Debian  
    
- name: "add users"
  include_role:
    name: geerlingguy.docker
    tasks_from: docker-users

- name: "create ~/semaphore folder"
  ansible.builtin.file:
    path: "~/semaphore" 
    state: "directory"

- name: "Copy docker-compose file"
  ansible.builtin.copy:
    src: "files/docker-compose.yaml"
    dest: "~/semaphore/"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: ~/semaphore
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: ~/semaphore
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output